/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: lildrstrange11 (https://sketchfab.com/lildrstrange11)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/kevin-the-cube-9786cbc1a5dc4a8ba5361813c1283bb3
Title: Kevin The Cube
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Hero3DModel(props) {
    const { nodes, materials } = useGLTF('models/kevin_the_cube/scene.gltf')
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_4.geometry}
                material={materials.Material}
                rotation={[Math.PI / 2, 0, 0]}
            />
        </group>
    )
}

useGLTF.preload('models/kevin_the_cube/scene.gltf')


